#include <stdio.h>
#define SIZE 10
int const a1=1;
int const a2=2;
int const a3=1;
int const a4=2;
int const a5=1;
int x1[SIZE]={1,1,1,1,1,1,1,1,1,1};
int x2[SIZE]={2,2,2,2,2,2,2,2,2,2};
int x3[SIZE]={3,3,3,3,3,3,3,3,3,3};
int x4[SIZE]={4,4,4,4,4,4,4,4,4,4};
int x5[SIZE]={5,5,5,5,5,5,5,5,5,5};
int y[SIZE];
void axpy5(int N, int *y, 
	    int a1, int *x1, int a2, int *x2, 
	    int a3, int *x3, int a4, int *x4,
	    int a5, int *x5) {

/*@ begin PerfTuning (
 def build {
   arg build_command = 'gcc';
   #arg libs = '-lrt';  # Only needed on linux
 } 
 def performance_counter {
   arg repetitions = 5;
 }
 def performance_params {  
   param UF[] = range(1,11);
   param CFLAGS[] = ['-O0', '-O1', '-O2', '-O3'];
   #constraint divisible_by_two = (UF % 2 == 0);
 }
 def input_params {
   param N[] = [1000000];
 }
 def input_vars {
   decl dynamic int x1[N] = random;
   decl dynamic int x2[N] = random;
   decl dynamic int x3[N] = random;
   decl dynamic int x4[N] = random;
   decl dynamic int x5[N] = random;
   decl dynamic int y[N] = 0;
   decl int a1 = random;
   decl int a2 = random;
   decl int a3 = random;
   decl int a4 = random;
   decl int a5 = random;
 }
 def search {
   arg algorithm = 'Exhaustive';
 }
) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [0.00713127, 0.00707012, 0.00708135, 0.00704405, 0.00702535] 
Tuned for specific problem sizes: 
  N = 1000000 
Best performance parameters: 
  CFLAGS = -O0 
  UF = 7 
--**/


  int n=N;
  register int i;

/*@ begin Loop ( 
  transform Unroll(ufactor=UF) 
  for (i=0; i<=n-1; i++)
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i]+a4*x4[i]+a5*x5[i];
) @*/
{
  int i;
  for (i=0; i<=n-7; i=i+7) {
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i]+a4*x4[i]+a5*x5[i];
    y[(i+1)]=y[(i+1)]+a1*x1[(i+1)]+a2*x2[(i+1)]+a3*x3[(i+1)]+a4*x4[(i+1)]+a5*x5[(i+1)];
    y[(i+2)]=y[(i+2)]+a1*x1[(i+2)]+a2*x2[(i+2)]+a3*x3[(i+2)]+a4*x4[(i+2)]+a5*x5[(i+2)];
    y[(i+3)]=y[(i+3)]+a1*x1[(i+3)]+a2*x2[(i+3)]+a3*x3[(i+3)]+a4*x4[(i+3)]+a5*x5[(i+3)];
    y[(i+4)]=y[(i+4)]+a1*x1[(i+4)]+a2*x2[(i+4)]+a3*x3[(i+4)]+a4*x4[(i+4)]+a5*x5[(i+4)];
    y[(i+5)]=y[(i+5)]+a1*x1[(i+5)]+a2*x2[(i+5)]+a3*x3[(i+5)]+a4*x4[(i+5)]+a5*x5[(i+5)];
    y[(i+6)]=y[(i+6)]+a1*x1[(i+6)]+a2*x2[(i+6)]+a3*x3[(i+6)]+a4*x4[(i+6)]+a5*x5[(i+6)];
  }
  for (i=n-((n-(0))%7); i<=n-1; i=i+1) 
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i]+a4*x4[i]+a5*x5[i];
}
/*@ end @*/
/*@ end @*/

}

int main(void) {
	axpy5(SIZE,y,a1,x1,a2,x2,a3,x3,a4,x4,a5,x5);
	printf ("Result y[SIZE]: %lf\n", y[SIZE-1]);
	printf ("Result y[SIZE]: %f\n", y[SIZE-1]);
	printf ("Result y[SIZE]: %e\n", y[SIZE-1]);

return 0;
}

